<?php

namespace Dcat\Admin\Grid\Actions;

use Dcat\Admin\Grid\RowAction;

class Delete extends RowAction
{
    /**
     * @return array|null|string
     */
    public function name()
    {
        return __('admin.delete');
    }

    public function render()
    {
        $this->setHtmlAttribute([
            'data-url' => "{$this->getResource()}/{$this->getKey()}",
            'data-action' => 'delete',

        ]);

        return parent::render(); // TODO: Change the autogenerated stub
    }
}
